spring.application.name=ms-reconciliation-core
server.port=${SERVER_PORT:9091}

# OpenAPI
springdoc.swagger-ui.path=/swagger-ui.html

# Security / Resource Server
spring.security.oauth2.resourceserver.jwt.issuer-uri=${JWT_ISSUER_URI:http://localhost:8081/realms/conciliaciones}

# CORS
app.cors.allowed-origins=${APP_CORS_ALLOWED_ORIGINS:http://localhost:4200}

# DataSource
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5440/conciliaciones_db}
spring.datasource.username=${DB_USERNAME:conci001}
spring.datasource.password=${DB_PASSWORD:conci001}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.default_schema=reconciliation

# Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# Logging
logging.level.root=INFO
logging.level.com.conciliaciones.reconciliation.core=DEBUG
