services:
  localstack:
    image: localstack/localstack:4.5.0
    container_name: localstack
    restart: unless-stopped
    ports:
      - "4566:4566"
    environment:
      SERVICES: ssm,s3,sqs
      DEBUG: 1
      AWS_DEFAULT_REGION: us-east-1
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      PERSISTENCE: 1
    volumes:
      - localstack_data:/var/lib/localstack
      - ../docker/localstack/init:/etc/localstack/init/ready.d
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - conciliaciones_net
      - conciliaciones-shared-net

volumes:
  localstack_data: