spring.application.name=ms-file-management
server.port=${SERVER_PORT:9092}

# OpenAPI
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

# Security / Resource Server
spring.security.oauth2.resourceserver.jwt.issuer-uri=${JWT_ISSUER_URI:http://localhost:8081/realms/conciliaciones}

# CORS
app.cors.allowed-origins=${APP_CORS_ALLOWED_ORIGINS:http://localhost:4200}

# DataSource
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5440/conciliaciones_db}
spring.datasource.username=${DB_USERNAME:conci001}
spring.datasource.password=${DB_PASSWORD:conci001}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.default_schema=reconciliation
spring.jpa.properties.hibernate.format_sql=true

# Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# Logging
logging.level.root=INFO
logging.level.com.conciliaciones.msfilemanagement=DEBUG

# AWS S3
app.aws.s3.enabled=${APP_AWS_S3_ENABLED:true}
app.aws.s3.localstack-enabled=${APP_AWS_S3_LOCALSTACK_ENABLED:true}
app.aws.s3.region=${APP_AWS_S3_REGION:us-east-1}
app.aws.s3.endpoint=${APP_AWS_S3_ENDPOINT:http://localhost:4566}
app.aws.s3.access-key=${APP_AWS_S3_ACCESS_KEY:test}
app.aws.s3.secret-key=${APP_AWS_S3_SECRET_KEY:test}
app.aws.s3.path-style-access-enabled=${APP_AWS_S3_PATH_STYLE:true}
app.aws.s3.presigned-url-duration-minutes=${APP_AWS_S3_PRESIGNED_DURATION_MINUTES:15}
app.aws.s3.default-bucket=${APP_AWS_S3_DEFAULT_BUCKET:conciliaciones-file-management-dev}
app.aws.s3.auto-create-default-bucket=${APP_AWS_S3_AUTO_CREATE_DEFAULT_BUCKET:true}
app.aws.s3.bucket-prefix=${APP_AWS_S3_BUCKET_PREFIX:fm}
