spring.application.name=ms-orchestrator
server.port=8080

# OpenAPI
springdoc.swagger-ui.path=/swagger-ui.html

# Security / Resource Server
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8081/realms/conciliaciones

# Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# Logging
logging.level.root=INFO
logging.level.com.conciliaciones.orchestrator=DEBUG
